---
functional:
  - У пользователей должна быть возможность зарегистрироваться на сайте при помощи логина и пароля/учетной записи на Github/учетной записи в Discord.
  - На сайте доступ к его игровому функционалу должен осуществляться после авторизации
  - Пользователь должен иметь возможность создавать на сайте игру с ботом.
  - Пользователь должен иметь возможность создавать на сайте закрытую игру с пригласительной ссылкой.
  - Пользователь должен иметь возможность создавать на сайте открытую игру, к которой могут присоединиться любые желающие.
  - Пользователь может управлять настройками игры во время создания - длительность, уровень сложности, тип игры (открытая, закрытая, с ботом), тэги, задание.
  - Пользователь должен видеть в режиме онлайн, как справляется с решением задания его оппонент.
  - Пользователь должен иметь возможность ввести свой программный код и проверить его.
  - Пользователь должен иметь возможность видеть вывод тестов после запуска проверки своего решения.
  - Пользователь должен иметь возможность сменить язык программирования во время игры.
  - Пользователь может присоединиться к игре по пригласительной ссылке. Как только пользователь перешел по пригласительной ссылке, игра начинается.
  - Сайт должен позволять выбрать пользователю задание на игру согласно выбранной сложности. Либо сайт назначит задание согласно выбранного уровня, которое определит случайно.
  - Сайт должен иметь чат, в котором зарегистрированные пользователи могут общаться.
  - Во время игры участники должны иметь возможность писать друг другу сообщения.
  - Сайт должен иметь возможность показать завершенную игру в записи.
  - Пользователи должны получать очки, на основе которых строится рейтинг за неделю, месяц и за все время
  - Пользователь должен иметь возможность бросать вызов другому пользователю.
  - Пользователи должны иметь возможность отправлять друг другу приватные сообщения.
  - Пользователь, получив инвайт, может либо отказаться, либо принять вызов.
  - Пользователь должен иметь возможность отменить свой вызов.
  - Пользователь должен иметь возможность сдаться во время игры.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть совместим с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен показывать лучших игроков за неделю, месяц, за все время на главной страница,  а также пользователей онлайн.
  - Сайт должен показывать игры, в которые в текущий момент можно присоединиться.
  - Пользователь должен иметь возможность просматривать профили других пользователей - количество побед, проигрышей, сдач, языки программирования, достижения, список завершенных игр с возможностью их просмотра, статистику активности.
  - Сайт должен уведомлять игроков об окончании игры звуковыми сигналами.
  - Пользователи могут следить за ходом чужой игры.
  - Сайт должен визуально уведомлять пользователей, что им брошен вызов.
  - Сайт должен отображать статус пользователей - готов к игре, играет.
  - Сайт должен позволять пользователю производить настройки своего профиля
  - Сайт должен уведомлять пользователя через всплывающие сообщения о том, что обновлен профиль
  - Сайт должен показывать пользователям описание заданий во время игры на двух языках (русском и английском).
  - Сайт должен позволять проводить турниры, когда играет команда против команды несколько раундов.
implicit:
  - Сайт должен уведомлять пользователя в браузере всплывающим уведомлением, что ему брошен вызов, пришло личное сообщение, когда он не на сайте.